import type { StudioProject, StudioStep } from "./studio.types";

export const studioSteps: StudioStep[] = [
  {
    id: "idea-capture",
    title: "捕捉想法",
    icon: "捕",
    description: "灵感收集与素材归档",
    outcome: "3 张素材卡",
    hint: "先把未经整理的灵感收进来，不急着判断好坏。",
    missing: "还可以补一个真实读者问题，让后续选题更稳。",
    primaryAction: "保存想法",
    wordTarget: "—",
    structure: "18%",
    natural: "—",
    publish: "—",
  },
  {
    id: "topic-generation",
    title: "选题生成",
    icon: "题",
    description: "确定读者、承诺与角度",
    outcome: "选题列表待确认",
    hint: "把文章从“我想写什么”收束为“读者为什么要读”。",
    missing: "还差一个更锋利的结果承诺，确认后再生成大纲。",
    primaryAction: "确认选题",
    wordTarget: "1200–2200",
    structure: "36%",
    natural: "—",
    publish: "—",
  },
  {
    id: "outline-planning",
    title: "大纲规划",
    icon: "纲",
    description: "文章骨架与段落任务",
    outcome: "5 段结构",
    hint: "先定结构，再让每一段承担明确任务。",
    missing: "案例段落还薄，建议补一个从灵感到初稿的真实过程。",
    primaryAction: "采用大纲",
    wordTarget: "1800",
    structure: "58%",
    natural: "—",
    publish: "—",
  },
  {
    id: "drafting",
    title: "撰写初稿",
    icon: "写",
    description: "正文生成与段落展开",
    outcome: "1260 字初稿",
    hint: "围绕大纲快速形成可编辑初稿，不在这一阶段追求完美。",
    missing: "“发布前检查”段落仍是空壳，需要补具体清单。",
    primaryAction: "生成下一段",
    wordTarget: "1800",
    structure: "72%",
    natural: "45%",
    publish: "—",
  },
  {
    id: "polishing",
    title: "润色改写",
    icon: "润",
    description: "节奏、标题与表达优化",
    outcome: "开头已改写",
    hint: "提升可读性：删掉绕路表达，让重点更早出现。",
    missing: "标题仍偏说明文，可以再改成更结果导向。",
    primaryAction: "应用改写",
    wordTarget: "1800",
    structure: "80%",
    natural: "62%",
    publish: "—",
  },
  {
    id: "humanizing",
    title: "去 AI 味",
    icon: "去",
    description: "人味、经验与语气校准",
    outcome: "4 处待处理",
    hint: "检查模板化、过度顺滑和缺少个人判断的位置。",
    missing: "还需要补入一处个人失败经验，抵消方法论腔。",
    primaryAction: "检查表达",
    wordTarget: "1800",
    structure: "82%",
    natural: "78%",
    publish: "—",
  },
  {
    id: "image-planning",
    title: "文章配图",
    icon: "图",
    description: "封面、信息图与段落插图",
    outcome: "4 张图位",
    hint: "让图片承担解释任务，而不是只做装饰。",
    missing: "封面标题需要压缩到 12 字以内。",
    primaryAction: "生成配图建议",
    wordTarget: "1800",
    structure: "84%",
    natural: "82%",
    publish: "40%",
  },
  {
    id: "publishing",
    title: "排版发布",
    icon: "发",
    description: "渠道适配与发布检查",
    outcome: "6/8 通过",
    hint: "完成发布前检查：标题、摘要、封面、格式与 CTA。",
    missing: "摘要与文末行动还需要更具体。",
    primaryAction: "准备发布",
    wordTarget: "1800",
    structure: "92%",
    natural: "86%",
    publish: "88%",
  },
];

export const initialStudioProject: StudioProject = {
  title: "如何把零散灵感变成一篇能发布的深度文章",
  ideas: ["起号阶段的真实卡点", "工作台价值", "可用类比"],
  writingIntent: "帮助刚开始稳定输出的知识型自媒体作者，把零散灵感推进为可发布文章。",
  confirmedTopic: "把零散灵感变成可发布文章：一套自媒体写作工作台",
  outline: ["开场：创作者真正卡住的不是写字", "为什么需要固定工作流", "8 步工作台拆解", "AI 应该在什么位置介入", "发布前检查清单"],
  draft: "很多自媒体作者的问题，不是没有灵感，而是灵感一旦进入写作阶段就会散掉。\n\n你可能在通勤时想到一个观点，在评论区看到一个读者问题，又在别人的文章里发现一个案例。但真正打开文档时，这些东西并不会自动变成一篇文章。\n\n所以我更建议把写作看成一个工作台，而不是一个空白文档。工作台的意义，是让每一步都有明确的输入和输出：先捕捉想法，再澄清选题，接着生成大纲、写初稿、润色、去 AI 味、配图，最后排版发布。",
  polishedDraft: "很多创作者并不缺灵感。真正困难的是：那些零散想法，一到写作时就散成了碎片。",
  imageBrief: "清爽的内容创作工作台界面，左侧为 8 步创作流程，右侧为文章编辑区与当前步骤 Agent。浅青灰背景，青绿色主行动，深墨蓝用于 Agent 区域，不出现机器人形象。",
  artifacts: {},
};
